### ISSUE TITLE
CapturePointHUD disappears if you are inside a transparent object or hover over it

### ISSUE THREAD

**Issue by verysecrethero** [teamfisk/TacticalZ#128]
CapturePointHUD disappears if you are inside a transparent object or hover over it
1. Take any transparent sphere
2. Stand inside it or
2b. Make sure the HUD goes "into" the sphere while standing outside it
3. now the HUD will disappear

**Comment by Tleety** [comment]
This is because whoever made the HUD failed to uncheck "DepthSorting" in the component
